export const SET_ALL_DATA = "COUNTRIES/SET_ALL_DATA";
export const ADD_CHOSEN_COUNTRY = "COUNTRIES/ADD_CHOSEN_COUNTRY";
export const SHOW_ALL_COUNTRIES = "COUNTRIES/SHOW_ALL_COUNTRIES";
export const SET_ALL_COUNTRIES_NAMES = "COUNTRIES/SET_ALL_COUNTRIES_NAMES";
export const REMOVE_COUNTRY = "COUNTRIES/REMOVE_COUNTRY";